require '../rake_helper'

define_source_tasks "protein_chemicals" => "http://stitch.embl.de:8080/download/protein_chemical.links.v2.0.tsv.gz",
  "chemicals" => "http://stitch.embl.de:8080/download/chemical.aliases.v2.0.tsv.gz"

process_tsv :protein_chemical, 'protein_chemicals',
  :native => 1,
  :grep => "9606\.", 
  :fix => lambda{|l| l.sub(/9606\./,'')},
  :keep_empty => true do

  headers ['Ensembl Protein ID', 'Chemical', 'Score']
end

$grep_re = []
process_tsv :chemicals, 'chemicals',
  :grep    => $grep_re,
  :exclude => proc{|l| p = l.split(/\t/); p[0] == p[1]} do

  $grep_re.replace CMD.cmd('cut', "-f" => 2, :in => File.open('protein_chemical')).read.split(/\n/).collect{|v| v.split(/\t/)}.flatten

  headers ['Chemical ID', 'Name', 'Source']
end

