require File.join(File.dirname(__FILE__),'../../lib/rake_functions.rb')
require 'rbbt/util/open'

data_files = {
  "protein_chemicals" => "http://stitch.embl.de:8080/download/protein_chemical.links.v2.0.tsv.gz",
  "chemical_aliases" => "http://stitch.embl.de:8080/download/chemical.aliases.v2.0.tsv.gz",
}

data_files.each do |name, url|
  file File.join('orig', name) do |t|
    Open.write(t.name, Open.read(url, :cache => false))
  end
end

file :gene_chemical => 'orig/protein_chemicals' do |t|
  data = Open.to_hash(t.prerequisites.first, :native => 1, :extra => [0,2], :exclude => lambda{|l| l !~ /9606\./}, :keep_empty => true)
  File.open(t.name, 'w') do |f|
    f.puts "#" + %w(Gene_ENSP Chemical Score) * "\t"
    data.each do |gene, values|
      f.puts "#{ gene.sub(/9606\./,'') }\t#{values.collect{|v| v * "|"} * "\t" }"
    end
  end
end

task :default => [:gene_chemical]
