require 'rbbt/util/open'

data_files = {
  "matador" => "http://matador.embl.de/media/download/matador.tsv.gz"
}

data_files.each do |name, url|
  file File.join('orig', name) do |t|
    Open.write(t.name, Open.read(url, :cache => false))
  end
end

file :gene_drug => 'orig/matador' do |t|
  data = Open.to_hash(t.prerequisites.first, :native => 1, :fix => lambda{|l| l.sub(/9606./,'')}, :extra => [3,7,8,9,10,11,12])
  File.open(t.name, 'w') do |f|
    f.puts "#" + %w(Chemical Gene Score Annotation Mesh_Score Mesh_Annotation Matador_Score Matador_Annotation) * "\t"
    data.each do |gene, values|
      f.puts "#{ gene }\t#{values.collect{|v| v * "|" } * "\t"}"
    end
  end
end



task :default => [:gene_drug]
